In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [6]:
ar = np.array(l)

In [7]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(1)

array(1)

In [10]:
a = [2,3,4]

In [12]:
np.asanyarray(a)

array([2, 3, 4])

In [14]:
b = np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [15]:
a = np.array(l)

In [16]:
c=a

In [17]:
c

array([1, 2, 3, 4])

In [18]:
a

array([1, 2, 3, 4])

In [19]:
c[0]=100

In [20]:
c

array([100,   2,   3,   4])

In [21]:
a

array([100,   2,   3,   4])

In [22]:
d = np.copy(a)

In [23]:
a

array([100,   2,   3,   4])

In [24]:
d

array([100,   2,   3,   4])

In [25]:
a[1]=400

In [26]:
a

array([100, 400,   3,   4])

In [27]:
d

array([100,   2,   3,   4])

In [29]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [32]:
ite= (i*i for i in range(5))

In [34]:
np.fromiter(ite,float)

array([ 0.,  1.,  4.,  9., 16.])

In [35]:
np.fromstring('234 234',sep=' ')

array([234., 234.])

In [37]:
np.fromstring('2,3,42,34',sep=',')

array([ 2.,  3., 42., 34.])

In [38]:
i = [2,3,4,5,6]

In [39]:
ar = np.array(l)

In [40]:
ar.ndim

1

In [41]:
ar2 = np.array([[1,2,3],[4,5,6]])

In [42]:
ar2.ndim

2

In [43]:
ar.size

4

In [44]:
ar2.size

6

In [47]:
ar.shape

(4,)

In [48]:
ar2.shape

(2, 3)

In [49]:
ar.dtype

dtype('int32')

In [50]:
ar2.dtype

dtype('int32')

In [53]:
ar22 = np.array([(1.4,45,45),(23,45,66)])

In [54]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [55]:
ar22.dtype

dtype('float64')

In [56]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [57]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [58]:
np.arange(2.3,5.6,.1)

array([2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5])

In [59]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [61]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [63]:
np.ones(4)

array([1., 1., 1., 1.])

In [69]:
on=np.ones((2,3,2))
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [70]:
on+=5
on

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [73]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [74]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [75]:
 np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [76]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [77]:
np.random.randn(3,4)

array([[ 0.53024874,  0.78675572, -1.1326721 ,  0.42337414],
       [-2.03834402, -0.56378318, -0.77495858,  0.43622597],
       [-0.3195738 , -0.42856538, -0.56103269, -1.01088088]])

In [80]:
arr = np.random.randn(3,4)

In [81]:
import pandas as pd

In [82]:
pd.DataFrame(arr)

0         1         2         3
0 -0.743003 -0.057522  0.533176  0.587784
1 -0.282583 -1.500447 -0.667886 -0.524952
2 -0.078457 -1.168392  0.304674  0.217446

In [83]:
np.random.rand(3,4)

array([[0.59499169, 0.37874481, 0.68063818, 0.30198643],
       [0.09700892, 0.65025791, 0.65812273, 0.39267035],
       [0.45437533, 0.27021198, 0.24549719, 0.79259846]])

In [85]:
np.random.randint(1,110,(2,3))

array([[ 90,  98,  94],
       [109,   8,   7]])

In [87]:
arr = np.random.rand(3,4)
arr

array([[0.67110939, 0.6418988 , 0.93353122, 0.11385187],
       [0.98804842, 0.72850334, 0.85389443, 0.25280901],
       [0.6290184 , 0.1587794 , 0.0607561 , 0.42078201]])

In [88]:
arr.reshape(6,-1)

array([[0.67110939, 0.6418988 ],
       [0.93353122, 0.11385187],
       [0.98804842, 0.72850334],
       [0.85389443, 0.25280901],
       [0.6290184 , 0.1587794 ],
       [0.0607561 , 0.42078201]])

In [93]:
arr1= arr.reshape(6,-123456789)

In [94]:
arr1

array([[0.67110939, 0.6418988 ],
       [0.93353122, 0.11385187],
       [0.98804842, 0.72850334],
       [0.85389443, 0.25280901],
       [0.6290184 , 0.1587794 ],
       [0.0607561 , 0.42078201]])

In [95]:
arr1[1][1]

0.1138518734263565

In [96]:
arr1[2:5,1] 

array([0.72850334, 0.25280901, 0.1587794 ])

In [97]:
arr = np.random.randint(1,100,(5,5))
arr

array([[41, 34,  7,  8, 75],
       [40,  1, 97,  3, 95],
       [ 8, 41, 81, 38, 66],
       [50, 97, 66, 23,  6],
       [36, 84, 11, 83, 43]])

In [98]:
arr>50

array([[False, False, False, False,  True],
       [False, False,  True, False,  True],
       [False, False,  True, False,  True],
       [False,  True,  True, False, False],
       [False,  True, False,  True, False]])

In [99]:
arr[arr>50]

array([75, 97, 95, 81, 66, 97, 66, 84, 83])

In [100]:
arr

array([[41, 34,  7,  8, 75],
       [40,  1, 97,  3, 95],
       [ 8, 41, 81, 38, 66],
       [50, 97, 66, 23,  6],
       [36, 84, 11, 83, 43]])

In [104]:
arr[2:4,[1,2]]

array([[41, 81],
       [97, 66]])

In [105]:
arr[0,0]

41

In [106]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [107]:
arr1

array([[2, 2, 1],
       [1, 1, 2],
       [1, 1, 2]])

In [108]:
arr2

array([[2, 2, 1],
       [2, 2, 1],
       [2, 1, 1]])

In [109]:
arr1+arr2

array([[4, 4, 2],
       [3, 3, 3],
       [3, 2, 3]])

In [110]:
arr1*arr2

array([[4, 4, 1],
       [2, 2, 2],
       [2, 1, 2]])

In [112]:
arr1@arr2

array([[10,  9,  5],
       [ 8,  6,  4],
       [ 8,  6,  4]])

In [113]:
arr1/0

C:\Users\nikhi\AppData\Local\Temp\ipykernel_6136\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [114]:
arr1**2

array([[4, 4, 1],
       [1, 1, 4],
       [1, 1, 4]])

In [115]:
arr = np.zeros((4,4))

In [116]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [118]:
row = np.array([1,2,3,4])
row

array([1, 2, 3, 4])

In [119]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [120]:
row.T

array([1, 2, 3, 4])

In [121]:
col = np.array([[1,2,3,4]])
col

array([[1, 2, 3, 4]])

In [122]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [123]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [124]:
arr11 = np.random.randint(1,4,(3,4))

In [125]:
arr11

array([[1, 1, 1, 1],
       [3, 3, 2, 3],
       [2, 1, 2, 3]])

In [126]:
np.sqrt(arr11)

array([[1.        , 1.        , 1.        , 1.        ],
       [1.73205081, 1.73205081, 1.41421356, 1.73205081],
       [1.41421356, 1.        , 1.41421356, 1.73205081]])

In [127]:
np.exp(arr11)

array([[ 2.71828183,  2.71828183,  2.71828183,  2.71828183],
       [20.08553692, 20.08553692,  7.3890561 , 20.08553692],
       [ 7.3890561 ,  2.71828183,  7.3890561 , 20.08553692]])

In [128]:
np.log10(arr11)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.47712125, 0.47712125, 0.30103   , 0.47712125],
       [0.30103   , 0.        , 0.30103   , 0.47712125]])