In [2]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))

In [3]:
arr

array([[3, 6, 3, 8],
       [1, 7, 7, 1],
       [7, 4, 5, 3]])

In [4]:
arr.reshape(6,2)

array([[3, 6],
       [3, 8],
       [1, 7],
       [7, 1],
       [7, 4],
       [5, 3]])

In [5]:
arr.reshape(3,6)

ValueError: cannot reshape array of size 12 into shape (3,6)

In [6]:
arr.flatten()

array([3, 6, 3, 8, 1, 7, 7, 1, 7, 4, 5, 3])

In [7]:
arr1 = np.array([1,2,3,3,4])

In [8]:
arr1

array([1, 2, 3, 3, 4])

In [9]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [10]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 3, 4]])

In [11]:
arr

array([[3, 6, 3, 8],
       [1, 7, 7, 1],
       [7, 4, 5, 3]])

In [12]:
np.squeeze(arr)

array([[3, 6, 3, 8],
       [1, 7, 7, 1],
       [7, 4, 5, 3]])

In [15]:
data = np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [16]:
np.squeeze(data)

array([1, 2, 3])

In [18]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [20]:
np.roll(arr1,2)

array([3, 4, 1, 2, 3])

In [21]:
np.roll(arr1,3)

array([3, 3, 4, 1, 2])

In [22]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [23]:
arr1 = np.random.randint(1,10,(3,3))

In [24]:
arr2 = np.random.randint(1,10,(3,3))

In [25]:
arr1

array([[9, 7, 9],
       [7, 3, 5],
       [5, 1, 7]])

In [26]:
arr2

array([[5, 8, 6],
       [1, 3, 8],
       [8, 4, 4]])

In [27]:
arr1+arr2

array([[14, 15, 15],
       [ 8,  6, 13],
       [13,  5, 11]])

In [28]:
arr1*arr2

array([[45, 56, 54],
       [ 7,  9, 40],
       [40,  4, 28]])

In [29]:
arr1/arr2

array([[1.8  , 0.875, 1.5  ],
       [7.   , 1.   , 0.625],
       [0.625, 0.25 , 1.75 ]])

In [30]:
arr1-arr2

array([[ 4, -1,  3],
       [ 6,  0, -3],
       [-3, -3,  3]])

In [31]:
arr1%arr2

array([[4, 7, 3],
       [0, 0, 5],
       [5, 1, 3]])

In [32]:
arr1**arr2

array([[  59049, 5764801,  531441],
       [      7,      27,  390625],
       [ 390625,       1,    2401]])

In [33]:
arr1&arr2

array([[1, 0, 0],
       [1, 3, 0],
       [0, 0, 4]])

In [34]:
~arr1

array([[-10,  -8, -10],
       [ -8,  -4,  -6],
       [ -6,  -2,  -8]])

In [35]:
arr1 | arr2

array([[13, 15, 15],
       [ 7,  3, 13],
       [13,  5,  7]])

In [36]:
arr1>arr2

array([[ True, False,  True],
       [ True, False, False],
       [False, False,  True]])

In [38]:
arr=np.array(['sudb','kumar'])

In [39]:
arr

array(['sudb', 'kumar'], dtype='<U5')

In [41]:
np.char.upper(arr)

array(['SUDB', 'KUMAR'], dtype='<U5')

In [42]:
np.char.title(arr)

array(['Sudb', 'Kumar'], dtype='<U5')

In [43]:
np.char.capitalize(arr)

array(['Sudb', 'Kumar'], dtype='<U5')

In [44]:
arr1

array([[9, 7, 9],
       [7, 3, 5],
       [5, 1, 7]])

In [46]:
np.sin(arr1)

array([[ 0.41211849,  0.6569866 ,  0.41211849],
       [ 0.6569866 ,  0.14112001, -0.95892427],
       [-0.95892427,  0.84147098,  0.6569866 ]])

In [47]:
np.cos(arr1)

array([[-0.91113026,  0.75390225, -0.91113026],
       [ 0.75390225, -0.9899925 ,  0.28366219],
       [ 0.28366219,  0.54030231,  0.75390225]])

In [48]:
np.tan(arr1)

array([[-0.45231566,  0.87144798, -0.45231566],
       [ 0.87144798, -0.14254654, -3.38051501],
       [-3.38051501,  1.55740772,  0.87144798]])

In [50]:
np.tanh(arr1)

array([[0.99999997, 0.99999834, 0.99999997],
       [0.99999834, 0.99505475, 0.9999092 ],
       [0.9999092 , 0.76159416, 0.99999834]])

In [52]:
np.log10(arr1)

array([[0.95424251, 0.84509804, 0.95424251],
       [0.84509804, 0.47712125, 0.69897   ],
       [0.69897   , 0.        , 0.84509804]])

In [54]:
np.exp(arr1)

array([[8.10308393e+03, 1.09663316e+03, 8.10308393e+03],
       [1.09663316e+03, 2.00855369e+01, 1.48413159e+02],
       [1.48413159e+02, 2.71828183e+00, 1.09663316e+03]])

In [55]:
np.sqrt(arr1)

array([[3.        , 2.64575131, 3.        ],
       [2.64575131, 1.73205081, 2.23606798],
       [2.23606798, 1.        , 2.64575131]])

In [57]:
np.power(arr1,2)

array([[81, 49, 81],
       [49,  9, 25],
       [25,  1, 49]], dtype=int32)

In [58]:
np.mean(arr1)

5.888888888888889

In [60]:
np.median(arr1)

7.0

In [61]:
np.std(arr1)

2.5141574442188355

In [62]:
np.var(arr1)

6.320987654320987

In [63]:
np.max(arr1)

9

In [64]:
np.min(arr1)

1

In [4]:
arr=np.array([4,3,5,6,5,678,5,74,5,6])

In [66]:
arr

array([  4,   3,   5,   6,   5, 678,   5,  74,   5,   6])

In [67]:
np.sort(arr)

array([  3,   4,   5,   5,   5,   5,   6,   6,  74, 678])

In [69]:
np.searchsorted(arr,4)

2

In [71]:
arr1 = np.array([0,234,34,0,0,0,0])

In [72]:
np.count_nonzero(arr1)

2

In [73]:
arr

array([  4,   3,   5,   6,   5, 678,   5,  74,   5,   6])

In [5]:
#it is used to perform element wise
np.where(arr>6)

(array([5, 7], dtype=int64),)

In [75]:
np.extract(arr>6,arr)

array([678,  74])

In [76]:
arr

array([  4,   3,   5,   6,   5, 678,   5,  74,   5,   6])

In [77]:
arr.byteswap()

array([   67108864,    50331648,    83886080,   100663296,    83886080,
       -1509818368,    83886080,  1241513984,    83886080,   100663296])

In [78]:
arr

array([  4,   3,   5,   6,   5, 678,   5,  74,   5,   6])

In [80]:
a = np.copy(arr)
a

array([  4,   3,   5,   6,   5, 678,   5,  74,   5,   6])

In [81]:
b = arr.view()

In [82]:
b

array([  4,   3,   5,   6,   5, 678,   5,  74,   5,   6])

In [83]:
arr

array([  4,   3,   5,   6,   5, 678,   5,  74,   5,   6])

In [84]:
b[0]=23

In [85]:
b

array([ 23,   3,   5,   6,   5, 678,   5,  74,   5,   6])

In [86]:
arr

array([ 23,   3,   5,   6,   5, 678,   5,  74,   5,   6])

In [87]:
import numpy.matlib as nm

In [88]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [89]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [90]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [10]:
arr1 = np.random.randint([[2,3],[4,5]])

In [11]:
arr2 = np.random.randint([[2,3],[4,5]])

In [93]:
np.dot(arr1,arr2)

array([[7, 6],
       [5, 3]])

In [94]:
arr1@arr2

array([[7, 6],
       [5, 3]])

In [3]:
import numpy as np
arr = np.array([4,3,6,7,3,344,67,22])

In [4]:
np.sort(arr)

array([  3,   3,   4,   6,   7,  22,  67, 344])

In [5]:
np.searchsorted(arr,34)

5

In [6]:
import numpy.matlib as nm

In [7]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [8]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
np.dot(arr1,arr2)

array([[5, 4],
       [2, 4]])